default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_booking_app_backend_development
  
test:
  <<: *default
  database: hotel_booking_app_backend_test

production:
  <<: *default
  database: hotel_booking_app_backend_production
  username: hotel_booking_app_backend
  password: <%= ENV["HOTEL_BOOKING_APP_BACKEND_DATABASE_PASSWORD"] %>
